### ISSUE TITLE
Missing 'ai' and 'ai2023' jupyter kernel

### ISSUE THREAD

**Issue by goupil35000** [Pat-Laub/DeepLearningForActuaries#1]
Hello,
Thank you for this great work and your videos on youtube. I'm very interested on how you are able to have in the same place all the contents to generate reveal slides, pdf, using python animation ...
I discovered Quarto two months ago and I began to use it for my reveal slides (I'm familiar with latex, python, ...).

I tried to use this repo to learn how you were able to do this. I think I resolved all of the problem with libraries (I don't use Anaconda).
At  this time I'm stuck on the problem of jupyter kernel. In configuration files, you define jupyter kernel as 'ai' and 'ai2023'. I don't know what are these: is-it special kernels you defined ? Are they available ?

Thanks for your answer.

Yves

**Comment by Pat-Laub** [comment]
Hi Yves,

Thanks for your kind words! You caught me in the middle of migrating from Keras v2 to Keras v3, so the Jupyter kernel situation is slightly more complicated than it will be after that migration is complete.

Basically Quarto needs to be able to find a Jupyter kernel which has everything in `scripts/requirements.in` installed. So if you have conda, the commands would look something like:

```
conda create -n ai2023 python=3.11
conda activate ai2023
pip install -r scripts/requirements.in
python -m ipykernel install --user --name ai2023

conda create -n ai python=3.11
conda activate ai
pip install -r scripts/requirements.in
pip install -U keras
python -m ipykernel install --user --name ai
```

The difference is the `ai` kernel is using [Keras v3](https://keras.io/keras_3/) (but installing that versions right now requires this two-step hacky approach until the next Tensorflow update is released), whereas the `ai2023` kernel is basically using Keras v2 (that is, the way I ran this course in 2023).

Once I've updated everything to Keras v3 this should be simplified (I'll remove `ai2023`), and even more so once that next Tensorflow release occurs!
Hopefully that helps.

Regards! Patrick

**Comment by goupil35000** [comment]
Hi Patrick,
Thank you very much. It solved the problem I had to launch the render process.
Now, I have another one. 

Here the message I have:


In [ 5/15] Lecture-3-Tabular-Data\categorical-variables.qmd
Starting ai2023 kernel...Done
  Cell 64/79: ''...
An error occurred while executing the following cell:
plot_model(model)
FileNotFoundError                         Traceback (most recent call last)
File c:\Users\yberg\anaconda3\envs\ai2023\Lib\site-packages\pydot\core.py:1753, in Dot.create(self, prog, format, encoding)
   1752 try:
-> 1753     stdout_data, stderr_data, process = call_graphviz(
   1754         program=prog,
   1755         arguments=arguments,
   1756         working_dir=tmp_dir,
   1757     )
   1758 except OSError as e:

Maybe related by my installation. But I removed all about python, keras, tensorflow ... on my machine and reinstalled anaconda and your requirements.

Thanks again for your help
Best regards,
Yves

**Comment by Pat-Laub** [comment]
Interesting, that one's a generic Keras dependency problem requiring Graphviz to call plot_model: e.g. [this link](https://ibkrcampus.com/ibkr-quant-news/plotting-an-architecture-of-tensorflow-keras-model-by-plot_model/). Installing pydot & graphviz in those environments should do the trick (though potentially the exact solution depends on which OS you have - I can't remember that part).

**Comment by Pat-Laub** [comment]
With Tensorflow 2.16's release, the two Jupyter kernels can be simplified back to having just one environment for all weeks, which I did in f9a22d1, so this temporary situation / original error shouldn't occur anymore.
